name: 'Grafting'
description: 'Installs and configures modules for migrations.'
type: 'Site'

install:
  - migrate_file_to_media
  - migrate_manifest
  - migrate_plus
  - migrate_process_markdown_to_html
  - migrate_scanner
  - migrate_skip_on_404
  - migrate_source_ui
  - migrate_tools
  - migrate_upgrade
  - migrate_url2link
  - views_migration
  - migration_tools
  - wordpress_migrate

config:
  import:
    # Import all of Migration Tools' modules config.
    migration_tools.settings:
      simple_config_update:
        drush_debug: 1
        drush_stop_on_error: 0
        debug: 0
        debug_level: '3'
